FROM python:3.7.2-alpine

# install dependencies
RUN apk update &&\
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add the app
COPY . /usr/src/app
COPY manage.py /usr/src/app

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh
RUN chmod +x manage.py


# run the server
CMD ["/usr/src/app/entrypoint.sh"]
# CMD python manage.py run -h 0.0.0.0
